Operation vector matrix
Kkkkkk18/spbu-python-course pull request #1
Opened 2024-10-02 23:41 UTC by Kkkkkk18

2024-10-03 11:53 UTC, Krekep requested changes
Помимо указанных недочётов необходимо, чтобы все Github Actions проходили проверку.

2024-10-03 11:53 UTC, Krekep commented on project/operation_matrix.py
> +    Return -> matrix addition
Посмотрите, как оформляются аргументы и возвращаемое значение в docstring. Бывают разные стандарты, можете глянуть на numpy стандарт (https://numpydoc.readthedocs.io/en/latest/format.html)

2024-10-03 11:53 UTC, Krekep commented on tests/test_operation_matrix.py
> +        mul([[1, 2]], [[1], [2], [3]])
Не хватает теста на умножение не квадратных матриц

2024-10-06 18:43 UTC, Kkkkkk18 commented
- [+] Сделать **приватный** `fork` данного репозитория.
- [+] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1h29GyiGds4PvkNSZqw_1VYGAAcFNKr0j-YzTJLWTHR4/edit?usp=sharing).
- [+] Добавить в совладельцы форка [@Krekep](https://github.com/Krekep)
- [+] Реализовать модуль, предоставляющий перечисленные ниже возможности.
  - [+] Операции над векторами: скалярное произведение, вычисление длины, нахождение угла между векторами.
  - [+] Операции над матрицами: сложение, умножение, транспонирование.
- [+] Добавить тесты покрывающие реализованную функциональность.
- [+] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.
- [+] Добавить статическую проверку типов с помощью `mypy` в `.github/workflows/`.

## Добавлено

* Тесты на ошибки
* Тест на умножение квадратных матриц
* Улучшен codestyle
* Улучшена документация
* :)

2024-10-06 20:36 UTC, Krekep approved these changes
Зачтено

2024-10-16 02:04 UTC, merged