Медведева. Task№3
Kkkkkk18/spbu-python-course pull request #3
Opened 2024-10-17 15:36 UTC by Kkkkkk18

- [x] Написать генераторное выражение для четырехмерного набора векторов [RGBA](https://en.wikipedia.org/wiki/RGBA_color_model) модели, где прозрачность принимает только чётные значения. Реализуйте функцию, возвращаю `i` элемент этого набора. Каждый цвет может принимать значения от 0 до 255 включительно, прозрачность может принимать значения от 0 до 100 включительно.
- [x] Реализовать функцию-генератор последовательности простых чисел. Обернуть её в декоратор, возвращающий `k`-е простое число (нумерация с единицы).
- [x] Добавить тесты покрывающие реализованную функциональность. Тесты должны использовать либо декоратор pytest.fixture, либо pytest.parametrize.

2024-10-19 08:59 UTC, Krekep requested changes
Не зачтено, т.к. не полностью выполнено задание

2024-10-19 08:59 UTC, Krekep commented on project/generators/primes_generator.py
> +    prime_gen = prime_generator()
Это не декоратор для генератора простых чисел.
Это просто функция, которая хранит инстанс генератора и обращается к нему

2024-12-25 13:04 UTC, Kkkkkk18 commented on project/generators/primes_generator.py
> +    prime_gen = prime_generator()
исправила

2024-12-26 11:32 UTC, Krekep approved these changes
Зачтено

2024-12-26 12:29 UTC, merged