Медведева. Task№4
Kkkkkk18/spbu-python-course pull request #4
Opened 2024-10-23 08:36 UTC by Kkkkkk18

- [x] Реализовать паттерн "пул потоков".
  - [x] Число потоков задаётся константой в классе пула или параметром конструктора.
  - [x] У каждого потока есть два состояния: ожидание задачи, выполнение задачи.
  - [x] Задача --- некая функция проводящая вычисления и возвращающая результат.
  - [x] Добавление задачи осуществляется с помощью метода `enqueue(task)`
  - [x] При добавлении задачи, если в пуле есть ожидающий поток, то он должен приступить к её выполнению. Иначе задача будет ожидать исполнения, пока не освободится какой-нибудь поток.
  - [x] Метод `dispose` должен завершать работу потоков. Уже запущенные задачи не прерываются, но новые задачи не принимаются на исполнение потоками из пула.
  - [x] Ограничения:
    - Разрешено использовать только пакет threading
    - Для каждого базового сценария должен быть написан несложный тест
    - Также должен быть написан тест, проверяющий, что в пуле действительно не менее `n` потоков
  - [x] Допущения:
    - Использование класса для реализации пула потоков необязательно

2024-10-23 09:28 UTC, Krekep requested changes
Всё хорошо, но необходимы косметические правки и дополнительный тест

2024-10-23 09:28 UTC, Krekep commented on project/operation_matrix_vector/operation_matrix.py
Не удаляйте файлы с прошлых заданий

2024-10-23 09:28 UTC, Krekep commented on project/thread_pool/thread_pool.py
> +    def enqueue(self, task):
Не хватает аннотации типов

2024-10-23 09:28 UTC, Krekep commented on project/thread_pool/thread_pool.py
> +            """
Кажется, что Вы перепутали местами docstring для класса и для __init__

2024-10-23 09:28 UTC, Krekep commented on project/thread_pool/thread_pool.py
> +    def __init__(self, num_threads):
Не хватает аннотации

2024-10-23 09:28 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +    ), f"Expected 5 tasks completed, got {len(tasks_executed)}"
Но ведь 4, а не 5, нет?

2024-10-23 09:28 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
Добавьте тест, проверяющий, что Вы можете добавить в тредпул задачи, после того, как `n` задач уже закончили работу, и новые задачи будут корректно обработаны. `n` --- количество потоков в пуле потоков

2024-10-24 18:14 UTC, Kkkkkk18 commented on project/thread_pool/thread_pool.py
> +    def enqueue(self, task):
Добавила

2024-10-24 18:14 UTC, Kkkkkk18 commented on project/thread_pool/thread_pool.py
> +            """
Поняла, исправила

2024-10-24 18:15 UTC, Kkkkkk18 commented on project/thread_pool/thread_pool.py
> +    def __init__(self, num_threads):
Исправила

2024-10-24 18:21 UTC, Kkkkkk18 commented
- Исправила ошибку в тесте
- Добавила аннотации
-Добавила тест, проверяющий, что можно добавить в тредпул задачи, после того, как n задач уже закончили работу, и новые задачи будут корректно обработаны. n --- количество потоков в пуле потоков

2024-10-25 08:33 UTC, Krekep approved these changes
Зачтено.
Из общих замечаний --- не удаляйте файлы с прошлых заданий. Если Вы сольёте текущий пулл-реквест с веткой main, то из ветки main пропадут файлы первого задания. Добавьте их обратно в ветку thread_pool и, соответственно в пулл-реквест. Также, возможно, я не совсем понятно написал в прошлый раз --- под аннотациями типов я подразумевал typehint у аргументов функции и самих функций, к примеру:
```
def enqueue(self, task: Callable) -> None
```
Здесь Callable говорит о том, что аргумент реализует соответствующий интерфейс, а `-> None`, что функция ничего не возвращает. Просьба добавить typehint в код. Если остались вопросы, то можете спрашивать

2024-10-29 00:41 UTC, merged